-- Optional: run only to reset the database (errors on first run are expected).
DROP TABLE Resposta CASCADE CONSTRAINTS;
DROP TABLE Etapa CASCADE CONSTRAINTS;
DROP TABLE Proves CASCADE CONSTRAINTS;
DROP TABLE Tumors CASCADE CONSTRAINTS;
DROP TABLE Cirugies CASCADE CONSTRAINTS;
DROP TABLE Funcion CASCADE CONSTRAINTS;
DROP TABLE Medics CASCADE CONSTRAINTS;
DROP TABLE Equip CASCADE CONSTRAINTS;
DROP TABLE Hospital CASCADE CONSTRAINTS;
DROP TABLE Departaments CASCADE CONSTRAINTS;
DROP TABLE Pacient CASCADE CONSTRAINTS;
DROP TABLE Tipus CASCADE CONSTRAINTS;
DROP TABLE Zones CASCADE CONSTRAINTS;
